application: stue-174803
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /Resources/favicon.ico
  static_files: /Resources/favicon.ico
  upload: /Resources/favicon.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /Resources
  static_dir: Resources

- url: /.*
  script: main.app

libraries:

- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
